# Generated by Django 3.2 on 2021-05-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('height', models.PositiveSmallIntegerField()),
                ('weight', models.PositiveSmallIntegerField()),
                ('sprite', models.URLField()),
                ('color', models.CharField(max_length=50)),
                ('generation', models.CharField(max_length=10)),
                ('evolution_chain', models.URLField()),
                ('stats', models.ManyToManyField(related_name='pokemons', to='api.PokemonStats')),
                ('types', models.ManyToManyField(related_name='pokemons', to='api.PokemonType')),
            ],
        ),
    ]
