# Generated by Django 3.2 on 2021-05-22 17:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210522_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonmove',
            name='versions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
    ]
