# Generated by Django 3.2 on 2021-05-31 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pokemonmove_versions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='moves',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='sprite',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='stats',
        ),
        migrations.DeleteModel(
            name='PokemonMove',
        ),
        migrations.DeleteModel(
            name='PokemonStat',
        ),
    ]
